//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace UclOpenHfVisualDataSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayCalibration
    {
    
        private DisplayIntrinsics _intrinsics;
    
        private DisplayExtrinsics _extrinsics;
    
        public DisplayCalibration()
        {
            _intrinsics = new DisplayIntrinsics();
            _extrinsics = new DisplayExtrinsics();
        }
    
        protected DisplayCalibration(DisplayCalibration other)
        {
            _intrinsics = other._intrinsics;
            _extrinsics = other._extrinsics;
        }
    
        /// <summary>
        /// Intrinsics
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("intrinsics")]
        [System.ComponentModel.DescriptionAttribute("Intrinsics")]
        public DisplayIntrinsics Intrinsics
        {
            get
            {
                return _intrinsics;
            }
            set
            {
                _intrinsics = value;
            }
        }
    
        /// <summary>
        /// Extrinsics
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("extrinsics")]
        [System.ComponentModel.DescriptionAttribute("Extrinsics")]
        public DisplayExtrinsics Extrinsics
        {
            get
            {
                return _extrinsics;
            }
            set
            {
                _extrinsics = value;
            }
        }
    
        public System.IObservable<DisplayCalibration> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayCalibration(this)));
        }
    
        public System.IObservable<DisplayCalibration> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayCalibration(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Intrinsics = " + _intrinsics + ", ");
            stringBuilder.Append("Extrinsics = " + _extrinsics);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayExtrinsics
    {
    
        private Vector3 _rotation;
    
        private Vector3 _translation;
    
        public DisplayExtrinsics()
        {
            _rotation = new Vector3();
            _translation = new Vector3();
        }
    
        protected DisplayExtrinsics(DisplayExtrinsics other)
        {
            _rotation = other._rotation;
            _translation = other._translation;
        }
    
        /// <summary>
        /// Rotation vector (radians)
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("rotation")]
        [System.ComponentModel.DescriptionAttribute("Rotation vector (radians)")]
        public Vector3 Rotation
        {
            get
            {
                return _rotation;
            }
            set
            {
                _rotation = value;
            }
        }
    
        /// <summary>
        /// Translation (in cm)
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("translation")]
        [System.ComponentModel.DescriptionAttribute("Translation (in cm)")]
        public Vector3 Translation
        {
            get
            {
                return _translation;
            }
            set
            {
                _translation = value;
            }
        }
    
        public System.IObservable<DisplayExtrinsics> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayExtrinsics(this)));
        }
    
        public System.IObservable<DisplayExtrinsics> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayExtrinsics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Rotation = " + _rotation + ", ");
            stringBuilder.Append("Translation = " + _translation);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayIntrinsics
    {
    
        private int _frameWidth;
    
        private int _frameHeight;
    
        private double _displayWidth;
    
        private double _displayHeight;
    
        public DisplayIntrinsics()
        {
            _frameWidth = 1920;
            _frameHeight = 1080;
            _displayWidth = 20D;
            _displayHeight = 15D;
        }
    
        protected DisplayIntrinsics(DisplayIntrinsics other)
        {
            _frameWidth = other._frameWidth;
            _frameHeight = other._frameHeight;
            _displayWidth = other._displayWidth;
            _displayHeight = other._displayHeight;
        }
    
        /// <summary>
        /// Frame width (px)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("frameWidth")]
        [System.ComponentModel.DescriptionAttribute("Frame width (px)")]
        public int FrameWidth
        {
            get
            {
                return _frameWidth;
            }
            set
            {
                _frameWidth = value;
            }
        }
    
        /// <summary>
        /// Frame height (px)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("frameHeight")]
        [System.ComponentModel.DescriptionAttribute("Frame height (px)")]
        public int FrameHeight
        {
            get
            {
                return _frameHeight;
            }
            set
            {
                _frameHeight = value;
            }
        }
    
        /// <summary>
        /// Display width (cm)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("displayWidth")]
        [System.ComponentModel.DescriptionAttribute("Display width (cm)")]
        public double DisplayWidth
        {
            get
            {
                return _displayWidth;
            }
            set
            {
                _displayWidth = value;
            }
        }
    
        /// <summary>
        /// Display width (cm)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("displayHeight")]
        [System.ComponentModel.DescriptionAttribute("Display width (cm)")]
        public double DisplayHeight
        {
            get
            {
                return _displayHeight;
            }
            set
            {
                _displayHeight = value;
            }
        }
    
        public System.IObservable<DisplayIntrinsics> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayIntrinsics(this)));
        }
    
        public System.IObservable<DisplayIntrinsics> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayIntrinsics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("FrameWidth = " + _frameWidth + ", ");
            stringBuilder.Append("FrameHeight = " + _frameHeight + ", ");
            stringBuilder.Append("DisplayWidth = " + _displayWidth + ", ");
            stringBuilder.Append("DisplayHeight = " + _displayHeight);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplaysCalibration
    {
    
        private DisplayCalibration _left;
    
        private DisplayCalibration _center;
    
        private DisplayCalibration _right;
    
        public DisplaysCalibration()
        {
            _left = new DisplayCalibration();
            _center = new DisplayCalibration();
            _right = new DisplayCalibration();
        }
    
        protected DisplaysCalibration(DisplaysCalibration other)
        {
            _left = other._left;
            _center = other._center;
            _right = other._right;
        }
    
        /// <summary>
        /// Left display calibration
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("left")]
        [System.ComponentModel.DescriptionAttribute("Left display calibration")]
        public DisplayCalibration Left
        {
            get
            {
                return _left;
            }
            set
            {
                _left = value;
            }
        }
    
        /// <summary>
        /// Center display calibration
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("center")]
        [System.ComponentModel.DescriptionAttribute("Center display calibration")]
        public DisplayCalibration Center
        {
            get
            {
                return _center;
            }
            set
            {
                _center = value;
            }
        }
    
        /// <summary>
        /// Right display calibration
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("right")]
        [System.ComponentModel.DescriptionAttribute("Right display calibration")]
        public DisplayCalibration Right
        {
            get
            {
                return _right;
            }
            set
            {
                _right = value;
            }
        }
    
        public System.IObservable<DisplaysCalibration> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplaysCalibration(this)));
        }
    
        public System.IObservable<DisplaysCalibration> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplaysCalibration(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Left = " + _left + ", ");
            stringBuilder.Append("Center = " + _center + ", ");
            stringBuilder.Append("Right = " + _right);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// The base class for creating experiment models.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("The base class for creating experiment models.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Experiment
    {
    
        private string _workflow;
    
        private string _commit;
    
        private string _repositoryUrl;
    
        public Experiment()
        {
        }
    
        protected Experiment(Experiment other)
        {
            _workflow = other._workflow;
            _commit = other._commit;
            _repositoryUrl = other._repositoryUrl;
        }
    
        /// <summary>
        /// Path to the workflow running the experiment.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("workflow", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Path to the workflow running the experiment.")]
        public string Workflow
        {
            get
            {
                return _workflow;
            }
            set
            {
                _workflow = value;
            }
        }
    
        /// <summary>
        /// Commit hash of the experiment repo.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("commit", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Commit hash of the experiment repo.")]
        public string Commit
        {
            get
            {
                return _commit;
            }
            set
            {
                _commit = value;
            }
        }
    
        /// <summary>
        /// The URL of the git repository used to version experiment source code.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("repositoryUrl", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The URL of the git repository used to version experiment source code.")]
        public string RepositoryUrl
        {
            get
            {
                return _repositoryUrl;
            }
            set
            {
                _repositoryUrl = value;
            }
        }
    
        public System.IObservable<Experiment> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Experiment(this)));
        }
    
        public System.IObservable<Experiment> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Experiment(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Workflow = " + _workflow + ", ");
            stringBuilder.Append("Commit = " + _commit + ", ");
            stringBuilder.Append("RepositoryUrl = " + _repositoryUrl);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Screen
    {
    
        private string _deviceType;
    
        private int _displayIndex;
    
        private double _targetRenderFrequency;
    
        private double _targetUpdateFrequency;
    
        private string _textureAssetsDirectory;
    
        private DisplaysCalibration _calibration;
    
        private double _brightness;
    
        private double _contrast;
    
        public Screen()
        {
            _deviceType = "Screen";
            _displayIndex = 1;
            _targetRenderFrequency = 60D;
            _targetUpdateFrequency = 120D;
            _textureAssetsDirectory = "Textures";
            _calibration = new DisplaysCalibration();
            _brightness = 0D;
            _contrast = 1D;
        }
    
        protected Screen(Screen other)
        {
            _deviceType = other._deviceType;
            _displayIndex = other._displayIndex;
            _targetRenderFrequency = other._targetRenderFrequency;
            _targetUpdateFrequency = other._targetUpdateFrequency;
            _textureAssetsDirectory = other._textureAssetsDirectory;
            _calibration = other._calibration;
            _brightness = other._brightness;
            _contrast = other._contrast;
        }
    
        /// <summary>
        /// Device type
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("deviceType")]
        [System.ComponentModel.DescriptionAttribute("Device type")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// Display index
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("displayIndex")]
        [System.ComponentModel.DescriptionAttribute("Display index")]
        public int DisplayIndex
        {
            get
            {
                return _displayIndex;
            }
            set
            {
                _displayIndex = value;
            }
        }
    
        /// <summary>
        /// Target render frequency
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("targetRenderFrequency")]
        [System.ComponentModel.DescriptionAttribute("Target render frequency")]
        public double TargetRenderFrequency
        {
            get
            {
                return _targetRenderFrequency;
            }
            set
            {
                _targetRenderFrequency = value;
            }
        }
    
        /// <summary>
        /// Target update frequency
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("targetUpdateFrequency")]
        [System.ComponentModel.DescriptionAttribute("Target update frequency")]
        public double TargetUpdateFrequency
        {
            get
            {
                return _targetUpdateFrequency;
            }
            set
            {
                _targetUpdateFrequency = value;
            }
        }
    
        /// <summary>
        /// Calibration directory
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("textureAssetsDirectory")]
        [System.ComponentModel.DescriptionAttribute("Calibration directory")]
        public string TextureAssetsDirectory
        {
            get
            {
                return _textureAssetsDirectory;
            }
            set
            {
                _textureAssetsDirectory = value;
            }
        }
    
        /// <summary>
        /// Screen calibration
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("calibration")]
        [System.ComponentModel.DescriptionAttribute("Screen calibration")]
        public DisplaysCalibration Calibration
        {
            get
            {
                return _calibration;
            }
            set
            {
                _calibration = value;
            }
        }
    
        /// <summary>
        /// Brightness
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("brightness")]
        [System.ComponentModel.DescriptionAttribute("Brightness")]
        public double Brightness
        {
            get
            {
                return _brightness;
            }
            set
            {
                _brightness = value;
            }
        }
    
        /// <summary>
        /// Contrast
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("contrast")]
        [System.ComponentModel.DescriptionAttribute("Contrast")]
        public double Contrast
        {
            get
            {
                return _contrast;
            }
            set
            {
                _contrast = value;
            }
        }
    
        public System.IObservable<Screen> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Screen(this)));
        }
    
        public System.IObservable<Screen> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Screen(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("DisplayIndex = " + _displayIndex + ", ");
            stringBuilder.Append("TargetRenderFrequency = " + _targetRenderFrequency + ", ");
            stringBuilder.Append("TargetUpdateFrequency = " + _targetUpdateFrequency + ", ");
            stringBuilder.Append("TextureAssetsDirectory = " + _textureAssetsDirectory + ", ");
            stringBuilder.Append("Calibration = " + _calibration + ", ");
            stringBuilder.Append("Brightness = " + _brightness + ", ");
            stringBuilder.Append("Contrast = " + _contrast);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenHfVisualRig
    {
    
        private string _version;
    
        private Screen _screen;
    
        public UclOpenHfVisualRig()
        {
            _version = "0.0.0-rc1";
            _screen = new Screen();
        }
    
        protected UclOpenHfVisualRig(UclOpenHfVisualRig other)
        {
            _version = other._version;
            _screen = other._screen;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("screen", Required=Newtonsoft.Json.Required.Always)]
        public Screen Screen
        {
            get
            {
                return _screen;
            }
            set
            {
                _screen = value;
            }
        }
    
        public System.IObservable<UclOpenHfVisualRig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenHfVisualRig(this)));
        }
    
        public System.IObservable<UclOpenHfVisualRig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenHfVisualRig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("Screen = " + _screen);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenHfVisualTaskLogic
    {
    
        private string _version;
    
        private string _name;
    
        private UclOpenHfVisualTaskParameters _taskParameters;
    
        public UclOpenHfVisualTaskLogic()
        {
            _version = "0.0.0-rc1";
            _name = "UclOpenHfVisual";
            _taskParameters = new UclOpenHfVisualTaskParameters();
        }
    
        protected UclOpenHfVisualTaskLogic(UclOpenHfVisualTaskLogic other)
        {
            _version = other._version;
            _name = other._name;
            _taskParameters = other._taskParameters;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        /// <summary>
        /// Name of the task logic
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        [System.ComponentModel.DescriptionAttribute("Name of the task logic")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        /// <summary>
        /// Parameters of the task logic
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("taskParameters", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Parameters of the task logic")]
        public UclOpenHfVisualTaskParameters TaskParameters
        {
            get
            {
                return _taskParameters;
            }
            set
            {
                _taskParameters = value;
            }
        }
    
        public System.IObservable<UclOpenHfVisualTaskLogic> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenHfVisualTaskLogic(this)));
        }
    
        public System.IObservable<UclOpenHfVisualTaskLogic> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenHfVisualTaskLogic(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("Name = " + _name + ", ");
            stringBuilder.Append("TaskParameters = " + _taskParameters);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenHfVisualTaskParameters
    {
    
        private double? _rngSeed;
    
        public UclOpenHfVisualTaskParameters()
        {
        }
    
        protected UclOpenHfVisualTaskParameters(UclOpenHfVisualTaskParameters other)
        {
            _rngSeed = other._rngSeed;
        }
    
        /// <summary>
        /// Seed of the random number generator
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("rngSeed")]
        [System.ComponentModel.DescriptionAttribute("Seed of the random number generator")]
        public double? RngSeed
        {
            get
            {
                return _rngSeed;
            }
            set
            {
                _rngSeed = value;
            }
        }
    
        public System.IObservable<UclOpenHfVisualTaskParameters> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenHfVisualTaskParameters(this)));
        }
    
        public System.IObservable<UclOpenHfVisualTaskParameters> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenHfVisualTaskParameters(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("RngSeed = " + _rngSeed);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Vector3
    {
    
        private double _x;
    
        private double _y;
    
        private double _z;
    
        public Vector3()
        {
            _x = 0D;
            _y = 0D;
            _z = 0D;
        }
    
        protected Vector3(Vector3 other)
        {
            _x = other._x;
            _y = other._y;
            _z = other._z;
        }
    
        /// <summary>
        /// X coordinate of the point
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("x")]
        [System.ComponentModel.DescriptionAttribute("X coordinate of the point")]
        public double X
        {
            get
            {
                return _x;
            }
            set
            {
                _x = value;
            }
        }
    
        /// <summary>
        /// Y coordinate of the point
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("y")]
        [System.ComponentModel.DescriptionAttribute("Y coordinate of the point")]
        public double Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }
    
        /// <summary>
        /// Z coordinate of the point
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("z")]
        [System.ComponentModel.DescriptionAttribute("Z coordinate of the point")]
        public double Z
        {
            get
            {
                return _z;
            }
            set
            {
                _z = value;
            }
        }
    
        public System.IObservable<Vector3> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Vector3(this)));
        }
    
        public System.IObservable<Vector3> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Vector3(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("X = " + _x + ", ");
            stringBuilder.Append("Y = " + _y + ", ");
            stringBuilder.Append("Z = " + _z);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<DisplayCalibration> source)
        {
            return Process<DisplayCalibration>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayExtrinsics> source)
        {
            return Process<DisplayExtrinsics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayIntrinsics> source)
        {
            return Process<DisplayIntrinsics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplaysCalibration> source)
        {
            return Process<DisplaysCalibration>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Experiment> source)
        {
            return Process<Experiment>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Screen> source)
        {
            return Process<Screen>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenHfVisualRig> source)
        {
            return Process<UclOpenHfVisualRig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenHfVisualTaskLogic> source)
        {
            return Process<UclOpenHfVisualTaskLogic>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenHfVisualTaskParameters> source)
        {
            return Process<UclOpenHfVisualTaskParameters>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Vector3> source)
        {
            return Process<Vector3>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayCalibration>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayExtrinsics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayIntrinsics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplaysCalibration>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Experiment>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Screen>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenHfVisualRig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenHfVisualTaskLogic>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenHfVisualTaskParameters>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Vector3>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<DisplayCalibration>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }
}