//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace UclOpenHfVisualDataSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayCalibration
    {
    
        private DisplayIntrinsics _intrinsics;
    
        private DisplayExtrinsics _extrinsics;
    
        public DisplayCalibration()
        {
            _intrinsics = new DisplayIntrinsics();
            _extrinsics = new DisplayExtrinsics();
        }
    
        protected DisplayCalibration(DisplayCalibration other)
        {
            _intrinsics = other._intrinsics;
            _extrinsics = other._extrinsics;
        }
    
        /// <summary>
        /// Intrinsics
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("intrinsics")]
        [System.ComponentModel.DescriptionAttribute("Intrinsics")]
        public DisplayIntrinsics Intrinsics
        {
            get
            {
                return _intrinsics;
            }
            set
            {
                _intrinsics = value;
            }
        }
    
        /// <summary>
        /// Extrinsics
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("extrinsics")]
        [System.ComponentModel.DescriptionAttribute("Extrinsics")]
        public DisplayExtrinsics Extrinsics
        {
            get
            {
                return _extrinsics;
            }
            set
            {
                _extrinsics = value;
            }
        }
    
        public System.IObservable<DisplayCalibration> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayCalibration(this)));
        }
    
        public System.IObservable<DisplayCalibration> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayCalibration(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Intrinsics = " + _intrinsics + ", ");
            stringBuilder.Append("Extrinsics = " + _extrinsics);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayExtrinsics
    {
    
        private Vector3 _rotation;
    
        private Vector3 _translation;
    
        public DisplayExtrinsics()
        {
            _rotation = new Vector3();
            _translation = new Vector3();
        }
    
        protected DisplayExtrinsics(DisplayExtrinsics other)
        {
            _rotation = other._rotation;
            _translation = other._translation;
        }
    
        /// <summary>
        /// Rotation vector (radians)
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("rotation")]
        [System.ComponentModel.DescriptionAttribute("Rotation vector (radians)")]
        public Vector3 Rotation
        {
            get
            {
                return _rotation;
            }
            set
            {
                _rotation = value;
            }
        }
    
        /// <summary>
        /// Translation (in cm)
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("translation")]
        [System.ComponentModel.DescriptionAttribute("Translation (in cm)")]
        public Vector3 Translation
        {
            get
            {
                return _translation;
            }
            set
            {
                _translation = value;
            }
        }
    
        public System.IObservable<DisplayExtrinsics> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayExtrinsics(this)));
        }
    
        public System.IObservable<DisplayExtrinsics> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayExtrinsics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Rotation = " + _rotation + ", ");
            stringBuilder.Append("Translation = " + _translation);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DisplayIntrinsics
    {
    
        private int _frameWidth;
    
        private int _frameHeight;
    
        private double _displayWidth;
    
        private double _displayHeight;
    
        public DisplayIntrinsics()
        {
            _frameWidth = 1920;
            _frameHeight = 1080;
            _displayWidth = 20D;
            _displayHeight = 15D;
        }
    
        protected DisplayIntrinsics(DisplayIntrinsics other)
        {
            _frameWidth = other._frameWidth;
            _frameHeight = other._frameHeight;
            _displayWidth = other._displayWidth;
            _displayHeight = other._displayHeight;
        }
    
        /// <summary>
        /// Frame width (px)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("frameWidth")]
        [System.ComponentModel.DescriptionAttribute("Frame width (px)")]
        public int FrameWidth
        {
            get
            {
                return _frameWidth;
            }
            set
            {
                _frameWidth = value;
            }
        }
    
        /// <summary>
        /// Frame height (px)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("frameHeight")]
        [System.ComponentModel.DescriptionAttribute("Frame height (px)")]
        public int FrameHeight
        {
            get
            {
                return _frameHeight;
            }
            set
            {
                _frameHeight = value;
            }
        }
    
        /// <summary>
        /// Display width (cm)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("displayWidth")]
        [System.ComponentModel.DescriptionAttribute("Display width (cm)")]
        public double DisplayWidth
        {
            get
            {
                return _displayWidth;
            }
            set
            {
                _displayWidth = value;
            }
        }
    
        /// <summary>
        /// Display width (cm)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("displayHeight")]
        [System.ComponentModel.DescriptionAttribute("Display width (cm)")]
        public double DisplayHeight
        {
            get
            {
                return _displayHeight;
            }
            set
            {
                _displayHeight = value;
            }
        }
    
        public System.IObservable<DisplayIntrinsics> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DisplayIntrinsics(this)));
        }
    
        public System.IObservable<DisplayIntrinsics> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DisplayIntrinsics(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("FrameWidth = " + _frameWidth + ", ");
            stringBuilder.Append("FrameHeight = " + _frameHeight + ", ");
            stringBuilder.Append("DisplayWidth = " + _displayWidth + ", ");
            stringBuilder.Append("DisplayHeight = " + _displayHeight);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// The base class for creating ucl-open experiment models.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("The base class for creating ucl-open experiment models.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Experiment
    {
    
        private string _workflow;
    
        private string _commit;
    
        private string _repositoryUrl;
    
        public Experiment()
        {
        }
    
        protected Experiment(Experiment other)
        {
            _workflow = other._workflow;
            _commit = other._commit;
            _repositoryUrl = other._repositoryUrl;
        }
    
        /// <summary>
        /// Path to the workflow running the experiment.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("workflow", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Path to the workflow running the experiment.")]
        public string Workflow
        {
            get
            {
                return _workflow;
            }
            set
            {
                _workflow = value;
            }
        }
    
        /// <summary>
        /// Commit hash of the experiment/rig repo.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("commit", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Commit hash of the experiment/rig repo.")]
        public string Commit
        {
            get
            {
                return _commit;
            }
            set
            {
                _commit = value;
            }
        }
    
        /// <summary>
        /// The URL of the git repository used to version experiment source code.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("repositoryUrl", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The URL of the git repository used to version experiment source code.")]
        public string RepositoryUrl
        {
            get
            {
                return _repositoryUrl;
            }
            set
            {
                _repositoryUrl = value;
            }
        }
    
        public System.IObservable<Experiment> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Experiment(this)));
        }
    
        public System.IObservable<Experiment> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Experiment(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Workflow = " + _workflow + ", ");
            stringBuilder.Append("Commit = " + _commit + ", ");
            stringBuilder.Append("RepositoryUrl = " + _repositoryUrl);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class MatrixArduino
    {
    
        private string _deviceType;
    
        private string _portName;
    
        private int _baudRate;
    
        private string _encoding;
    
        private string _newLine;
    
        private string _parity;
    
        private int _parityReplace;
    
        private int _dataBits;
    
        private string _stopBits;
    
        private string _handshake;
    
        private bool _discardNull;
    
        private bool _dtrEnable;
    
        private bool _rtsEnable;
    
        private int _readBufferSize;
    
        private int _writeBufferSize;
    
        private int _receivedBytesThreshold;
    
        private string _serialMessageSubjectName;
    
        public MatrixArduino()
        {
            _deviceType = "MatrixArduino";
            _baudRate = 9600;
            _newLine = "\r\n";
            _parity = "None";
            _parityReplace = 63;
            _dataBits = 8;
            _stopBits = "One";
            _handshake = "None";
            _discardNull = false;
            _dtrEnable = false;
            _rtsEnable = false;
            _readBufferSize = 4096;
            _writeBufferSize = 2048;
            _receivedBytesThreshold = 1;
            _serialMessageSubjectName = "SerialMessages";
        }
    
        protected MatrixArduino(MatrixArduino other)
        {
            _deviceType = other._deviceType;
            _portName = other._portName;
            _baudRate = other._baudRate;
            _encoding = other._encoding;
            _newLine = other._newLine;
            _parity = other._parity;
            _parityReplace = other._parityReplace;
            _dataBits = other._dataBits;
            _stopBits = other._stopBits;
            _handshake = other._handshake;
            _discardNull = other._discardNull;
            _dtrEnable = other._dtrEnable;
            _rtsEnable = other._rtsEnable;
            _readBufferSize = other._readBufferSize;
            _writeBufferSize = other._writeBufferSize;
            _receivedBytesThreshold = other._receivedBytesThreshold;
            _serialMessageSubjectName = other._serialMessageSubjectName;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("deviceType")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("portName", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        /// <summary>
        /// Baud rate for serial communication.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("baudRate")]
        [System.ComponentModel.DescriptionAttribute("Baud rate for serial communication.")]
        public int BaudRate
        {
            get
            {
                return _baudRate;
            }
            set
            {
                _baudRate = value;
            }
        }
    
        /// <summary>
        /// Optional text encoding for interpreting incoming bytes.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("encoding")]
        [System.ComponentModel.DescriptionAttribute("Optional text encoding for interpreting incoming bytes.")]
        public string Encoding
        {
            get
            {
                return _encoding;
            }
            set
            {
                _encoding = value;
            }
        }
    
        /// <summary>
        /// Line termination sequence used to delimit incoming messages.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("newLine")]
        [System.ComponentModel.DescriptionAttribute("Line termination sequence used to delimit incoming messages.")]
        public string NewLine
        {
            get
            {
                return _newLine;
            }
            set
            {
                _newLine = value;
            }
        }
    
        /// <summary>
        /// Parity checking mode for the serial port.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("parity")]
        [System.ComponentModel.DescriptionAttribute("Parity checking mode for the serial port.")]
        public string Parity
        {
            get
            {
                return _parity;
            }
            set
            {
                _parity = value;
            }
        }
    
        /// <summary>
        /// Byte used to replace invalid bytes detected by a parity error.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("parityReplace")]
        [System.ComponentModel.DescriptionAttribute("Byte used to replace invalid bytes detected by a parity error.")]
        public int ParityReplace
        {
            get
            {
                return _parityReplace;
            }
            set
            {
                _parityReplace = value;
            }
        }
    
        /// <summary>
        /// Number of data bits per serial frame.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("dataBits")]
        [System.ComponentModel.DescriptionAttribute("Number of data bits per serial frame.")]
        public int DataBits
        {
            get
            {
                return _dataBits;
            }
            set
            {
                _dataBits = value;
            }
        }
    
        /// <summary>
        /// Number of stop bits per serial frame.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("stopBits")]
        [System.ComponentModel.DescriptionAttribute("Number of stop bits per serial frame.")]
        public string StopBits
        {
            get
            {
                return _stopBits;
            }
            set
            {
                _stopBits = value;
            }
        }
    
        /// <summary>
        /// Hardware or software handshaking mode.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("handshake")]
        [System.ComponentModel.DescriptionAttribute("Hardware or software handshaking mode.")]
        public string Handshake
        {
            get
            {
                return _handshake;
            }
            set
            {
                _handshake = value;
            }
        }
    
        /// <summary>
        /// Whether to discard null bytes appearing in the serial stream.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("discardNull")]
        [System.ComponentModel.DescriptionAttribute("Whether to discard null bytes appearing in the serial stream.")]
        public bool DiscardNull
        {
            get
            {
                return _discardNull;
            }
            set
            {
                _discardNull = value;
            }
        }
    
        /// <summary>
        /// Whether to enable Data Terminal Ready (DTR) control line.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("dtrEnable")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable Data Terminal Ready (DTR) control line.")]
        public bool DtrEnable
        {
            get
            {
                return _dtrEnable;
            }
            set
            {
                _dtrEnable = value;
            }
        }
    
        /// <summary>
        /// Whether to enable Request To Send (RTS) control line.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("rtsEnable")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable Request To Send (RTS) control line.")]
        public bool RtsEnable
        {
            get
            {
                return _rtsEnable;
            }
            set
            {
                _rtsEnable = value;
            }
        }
    
        /// <summary>
        /// Size, in bytes, of the read buffer.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("readBufferSize")]
        [System.ComponentModel.DescriptionAttribute("Size, in bytes, of the read buffer.")]
        public int ReadBufferSize
        {
            get
            {
                return _readBufferSize;
            }
            set
            {
                _readBufferSize = value;
            }
        }
    
        /// <summary>
        /// Size, in bytes, of the write buffer.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("writeBufferSize")]
        [System.ComponentModel.DescriptionAttribute("Size, in bytes, of the write buffer.")]
        public int WriteBufferSize
        {
            get
            {
                return _writeBufferSize;
            }
            set
            {
                _writeBufferSize = value;
            }
        }
    
        /// <summary>
        /// Minimum number of bytes in the buffer that triggers a read event.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("receivedBytesThreshold")]
        [System.ComponentModel.DescriptionAttribute("Minimum number of bytes in the buffer that triggers a read event.")]
        public int ReceivedBytesThreshold
        {
            get
            {
                return _receivedBytesThreshold;
            }
            set
            {
                _receivedBytesThreshold = value;
            }
        }
    
        /// <summary>
        /// Name of the subject to which parsed serial messages are published.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("serialMessageSubjectName")]
        [System.ComponentModel.DescriptionAttribute("Name of the subject to which parsed serial messages are published.")]
        public string SerialMessageSubjectName
        {
            get
            {
                return _serialMessageSubjectName;
            }
            set
            {
                _serialMessageSubjectName = value;
            }
        }
    
        public System.IObservable<MatrixArduino> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new MatrixArduino(this)));
        }
    
        public System.IObservable<MatrixArduino> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new MatrixArduino(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("BaudRate = " + _baudRate + ", ");
            stringBuilder.Append("Encoding = " + _encoding + ", ");
            stringBuilder.Append("NewLine = " + _newLine + ", ");
            stringBuilder.Append("Parity = " + _parity + ", ");
            stringBuilder.Append("ParityReplace = " + _parityReplace + ", ");
            stringBuilder.Append("DataBits = " + _dataBits + ", ");
            stringBuilder.Append("StopBits = " + _stopBits + ", ");
            stringBuilder.Append("Handshake = " + _handshake + ", ");
            stringBuilder.Append("DiscardNull = " + _discardNull + ", ");
            stringBuilder.Append("DtrEnable = " + _dtrEnable + ", ");
            stringBuilder.Append("RtsEnable = " + _rtsEnable + ", ");
            stringBuilder.Append("ReadBufferSize = " + _readBufferSize + ", ");
            stringBuilder.Append("WriteBufferSize = " + _writeBufferSize + ", ");
            stringBuilder.Append("ReceivedBytesThreshold = " + _receivedBytesThreshold + ", ");
            stringBuilder.Append("SerialMessageSubjectName = " + _serialMessageSubjectName);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class MatrixArduinoData
    {
    
        private int _encoderCount;
    
        private int _lickCountLeft;
    
        private int _lickCountRight;
    
        private int _lastSyncPulseTime;
    
        private int _photodiodeVal;
    
        private int _currentMs;
    
        public MatrixArduinoData()
        {
        }
    
        protected MatrixArduinoData(MatrixArduinoData other)
        {
            _encoderCount = other._encoderCount;
            _lickCountLeft = other._lickCountLeft;
            _lickCountRight = other._lickCountRight;
            _lastSyncPulseTime = other._lastSyncPulseTime;
            _photodiodeVal = other._photodiodeVal;
            _currentMs = other._currentMs;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("encoderCount", Required=Newtonsoft.Json.Required.Always)]
        public int EncoderCount
        {
            get
            {
                return _encoderCount;
            }
            set
            {
                _encoderCount = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("lickCountLeft", Required=Newtonsoft.Json.Required.Always)]
        public int LickCountLeft
        {
            get
            {
                return _lickCountLeft;
            }
            set
            {
                _lickCountLeft = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("lickCountRight", Required=Newtonsoft.Json.Required.Always)]
        public int LickCountRight
        {
            get
            {
                return _lickCountRight;
            }
            set
            {
                _lickCountRight = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("lastSyncPulseTime", Required=Newtonsoft.Json.Required.Always)]
        public int LastSyncPulseTime
        {
            get
            {
                return _lastSyncPulseTime;
            }
            set
            {
                _lastSyncPulseTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("photodiodeVal", Required=Newtonsoft.Json.Required.Always)]
        public int PhotodiodeVal
        {
            get
            {
                return _photodiodeVal;
            }
            set
            {
                _photodiodeVal = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("currentMs", Required=Newtonsoft.Json.Required.Always)]
        public int CurrentMs
        {
            get
            {
                return _currentMs;
            }
            set
            {
                _currentMs = value;
            }
        }
    
        public System.IObservable<MatrixArduinoData> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new MatrixArduinoData(this)));
        }
    
        public System.IObservable<MatrixArduinoData> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new MatrixArduinoData(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("EncoderCount = " + _encoderCount + ", ");
            stringBuilder.Append("LickCountLeft = " + _lickCountLeft + ", ");
            stringBuilder.Append("LickCountRight = " + _lickCountRight + ", ");
            stringBuilder.Append("LastSyncPulseTime = " + _lastSyncPulseTime + ", ");
            stringBuilder.Append("PhotodiodeVal = " + _photodiodeVal + ", ");
            stringBuilder.Append("CurrentMs = " + _currentMs);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Screen
    {
    
        private string _deviceType;
    
        private int _displayIndex;
    
        private double _targetRenderFrequency;
    
        private double _targetUpdateFrequency;
    
        private string _textureAssetsDirectory;
    
        private System.Collections.Generic.Dictionary<string, DisplayCalibration> _calibration;
    
        private double _brightness;
    
        private double _contrast;
    
        public Screen()
        {
            _deviceType = "Screen";
            _displayIndex = 1;
            _targetRenderFrequency = 60D;
            _targetUpdateFrequency = 120D;
            _textureAssetsDirectory = "Textures";
            _brightness = 0D;
            _contrast = 1D;
        }
    
        protected Screen(Screen other)
        {
            _deviceType = other._deviceType;
            _displayIndex = other._displayIndex;
            _targetRenderFrequency = other._targetRenderFrequency;
            _targetUpdateFrequency = other._targetUpdateFrequency;
            _textureAssetsDirectory = other._textureAssetsDirectory;
            _calibration = other._calibration;
            _brightness = other._brightness;
            _contrast = other._contrast;
        }
    
        /// <summary>
        /// Device type
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("deviceType")]
        [System.ComponentModel.DescriptionAttribute("Device type")]
        public string DeviceType
        {
            get
            {
                return _deviceType;
            }
            set
            {
                _deviceType = value;
            }
        }
    
        /// <summary>
        /// Display index
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("displayIndex")]
        [System.ComponentModel.DescriptionAttribute("Display index")]
        public int DisplayIndex
        {
            get
            {
                return _displayIndex;
            }
            set
            {
                _displayIndex = value;
            }
        }
    
        /// <summary>
        /// Target render frequency
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("targetRenderFrequency")]
        [System.ComponentModel.DescriptionAttribute("Target render frequency")]
        public double TargetRenderFrequency
        {
            get
            {
                return _targetRenderFrequency;
            }
            set
            {
                _targetRenderFrequency = value;
            }
        }
    
        /// <summary>
        /// Target update frequency
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("targetUpdateFrequency")]
        [System.ComponentModel.DescriptionAttribute("Target update frequency")]
        public double TargetUpdateFrequency
        {
            get
            {
                return _targetUpdateFrequency;
            }
            set
            {
                _targetUpdateFrequency = value;
            }
        }
    
        /// <summary>
        /// Calibration directory
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("textureAssetsDirectory")]
        [System.ComponentModel.DescriptionAttribute("Calibration directory")]
        public string TextureAssetsDirectory
        {
            get
            {
                return _textureAssetsDirectory;
            }
            set
            {
                _textureAssetsDirectory = value;
            }
        }
    
        /// <summary>
        /// Calibration parameters for a set of named display monitors for visual stimuli
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("calibration")]
        [System.ComponentModel.DescriptionAttribute("Calibration parameters for a set of named display monitors for visual stimuli")]
        public System.Collections.Generic.Dictionary<string, DisplayCalibration> Calibration
        {
            get
            {
                return _calibration;
            }
            set
            {
                _calibration = value;
            }
        }
    
        /// <summary>
        /// Brightness
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("brightness")]
        [System.ComponentModel.DescriptionAttribute("Brightness")]
        public double Brightness
        {
            get
            {
                return _brightness;
            }
            set
            {
                _brightness = value;
            }
        }
    
        /// <summary>
        /// Contrast
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("contrast")]
        [System.ComponentModel.DescriptionAttribute("Contrast")]
        public double Contrast
        {
            get
            {
                return _contrast;
            }
            set
            {
                _contrast = value;
            }
        }
    
        public System.IObservable<Screen> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Screen(this)));
        }
    
        public System.IObservable<Screen> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Screen(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DeviceType = " + _deviceType + ", ");
            stringBuilder.Append("DisplayIndex = " + _displayIndex + ", ");
            stringBuilder.Append("TargetRenderFrequency = " + _targetRenderFrequency + ", ");
            stringBuilder.Append("TargetUpdateFrequency = " + _targetUpdateFrequency + ", ");
            stringBuilder.Append("TextureAssetsDirectory = " + _textureAssetsDirectory + ", ");
            stringBuilder.Append("Calibration = " + _calibration + ", ");
            stringBuilder.Append("Brightness = " + _brightness + ", ");
            stringBuilder.Append("Contrast = " + _contrast);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class SpinnakerCamera
    {
    
        private string _cameraType;
    
        private double _triggerFrequency;
    
        private double _exposureTime;
    
        private string _serialNumber;
    
        private double _gain;
    
        private int _binning;
    
        public SpinnakerCamera()
        {
            _cameraType = "Spinnaker";
            _triggerFrequency = 50D;
            _exposureTime = 15000D;
            _gain = 1D;
            _binning = 1;
        }
    
        protected SpinnakerCamera(SpinnakerCamera other)
        {
            _cameraType = other._cameraType;
            _triggerFrequency = other._triggerFrequency;
            _exposureTime = other._exposureTime;
            _serialNumber = other._serialNumber;
            _gain = other._gain;
            _binning = other._binning;
        }
    
        /// <summary>
        /// Camera type discriminator for Spinnaker devices.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("cameraType")]
        [System.ComponentModel.DescriptionAttribute("Camera type discriminator for Spinnaker devices.")]
        public string CameraType
        {
            get
            {
                return _cameraType;
            }
            set
            {
                _cameraType = value;
            }
        }
    
        /// <summary>
        /// The frequency at which the camera is triggered (in Hz).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("triggerFrequency")]
        [System.ComponentModel.DescriptionAttribute("The frequency at which the camera is triggered (in Hz).")]
        public double TriggerFrequency
        {
            get
            {
                return _triggerFrequency;
            }
            set
            {
                _triggerFrequency = value;
            }
        }
    
        /// <summary>
        /// The exposure time for the camera (in microseconds).
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("exposureTime")]
        [System.ComponentModel.DescriptionAttribute("The exposure time for the camera (in microseconds).")]
        public double ExposureTime
        {
            get
            {
                return _exposureTime;
            }
            set
            {
                _exposureTime = value;
            }
        }
    
        /// <summary>
        /// The serial number of the camera.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("serialNumber")]
        [System.ComponentModel.DescriptionAttribute("The serial number of the camera.")]
        public string SerialNumber
        {
            get
            {
                return _serialNumber;
            }
            set
            {
                _serialNumber = value;
            }
        }
    
        /// <summary>
        /// The camera gain.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("gain")]
        [System.ComponentModel.DescriptionAttribute("The camera gain.")]
        public double Gain
        {
            get
            {
                return _gain;
            }
            set
            {
                _gain = value;
            }
        }
    
        /// <summary>
        /// The binning setting for the camera.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("binning")]
        [System.ComponentModel.DescriptionAttribute("The binning setting for the camera.")]
        public int Binning
        {
            get
            {
                return _binning;
            }
            set
            {
                _binning = value;
            }
        }
    
        public System.IObservable<SpinnakerCamera> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new SpinnakerCamera(this)));
        }
    
        public System.IObservable<SpinnakerCamera> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new SpinnakerCamera(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CameraType = " + _cameraType + ", ");
            stringBuilder.Append("TriggerFrequency = " + _triggerFrequency + ", ");
            stringBuilder.Append("ExposureTime = " + _exposureTime + ", ");
            stringBuilder.Append("SerialNumber = " + _serialNumber + ", ");
            stringBuilder.Append("Gain = " + _gain + ", ");
            stringBuilder.Append("Binning = " + _binning);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class SyncQuad
    {
    
        private double _extentX;
    
        private double _extentY;
    
        private double _locationX;
    
        private double _locationY;
    
        public SyncQuad()
        {
        }
    
        protected SyncQuad(SyncQuad other)
        {
            _extentX = other._extentX;
            _extentY = other._extentY;
            _locationX = other._locationX;
            _locationY = other._locationY;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("extentX", Required=Newtonsoft.Json.Required.Always)]
        public double ExtentX
        {
            get
            {
                return _extentX;
            }
            set
            {
                _extentX = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("extentY", Required=Newtonsoft.Json.Required.Always)]
        public double ExtentY
        {
            get
            {
                return _extentY;
            }
            set
            {
                _extentY = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("locationX", Required=Newtonsoft.Json.Required.Always)]
        public double LocationX
        {
            get
            {
                return _locationX;
            }
            set
            {
                _locationX = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("locationY", Required=Newtonsoft.Json.Required.Always)]
        public double LocationY
        {
            get
            {
                return _locationY;
            }
            set
            {
                _locationY = value;
            }
        }
    
        public System.IObservable<SyncQuad> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new SyncQuad(this)));
        }
    
        public System.IObservable<SyncQuad> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new SyncQuad(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("ExtentX = " + _extentX + ", ");
            stringBuilder.Append("ExtentY = " + _extentY + ", ");
            stringBuilder.Append("LocationX = " + _locationX + ", ");
            stringBuilder.Append("LocationY = " + _locationY);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenHfVisualRig
    {
    
        private string _version;
    
        private Screen _screen;
    
        private SyncQuad _syncQuad;
    
        private MatrixArduino _arduino;
    
        private SpinnakerCamera _eyeCamera;
    
        public UclOpenHfVisualRig()
        {
            _version = "0.0.0-rc1";
            _screen = new Screen();
            _syncQuad = new SyncQuad();
            _arduino = new MatrixArduino();
            _eyeCamera = new SpinnakerCamera();
        }
    
        protected UclOpenHfVisualRig(UclOpenHfVisualRig other)
        {
            _version = other._version;
            _screen = other._screen;
            _syncQuad = other._syncQuad;
            _arduino = other._arduino;
            _eyeCamera = other._eyeCamera;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("screen", Required=Newtonsoft.Json.Required.Always)]
        public Screen Screen
        {
            get
            {
                return _screen;
            }
            set
            {
                _screen = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("syncQuad", Required=Newtonsoft.Json.Required.Always)]
        public SyncQuad SyncQuad
        {
            get
            {
                return _syncQuad;
            }
            set
            {
                _syncQuad = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("arduino", Required=Newtonsoft.Json.Required.Always)]
        public MatrixArduino Arduino
        {
            get
            {
                return _arduino;
            }
            set
            {
                _arduino = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("eyeCamera", Required=Newtonsoft.Json.Required.Always)]
        public SpinnakerCamera EyeCamera
        {
            get
            {
                return _eyeCamera;
            }
            set
            {
                _eyeCamera = value;
            }
        }
    
        public System.IObservable<UclOpenHfVisualRig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenHfVisualRig(this)));
        }
    
        public System.IObservable<UclOpenHfVisualRig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenHfVisualRig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("Screen = " + _screen + ", ");
            stringBuilder.Append("SyncQuad = " + _syncQuad + ", ");
            stringBuilder.Append("Arduino = " + _arduino + ", ");
            stringBuilder.Append("EyeCamera = " + _eyeCamera);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenHfVisualTaskLogic
    {
    
        private string _version;
    
        private string _name;
    
        private UclOpenHfVisualTaskParameters _taskParameters;
    
        public UclOpenHfVisualTaskLogic()
        {
            _version = "0.0.0-rc1";
            _name = "UclOpenHfVisual";
            _taskParameters = new UclOpenHfVisualTaskParameters();
        }
    
        protected UclOpenHfVisualTaskLogic(UclOpenHfVisualTaskLogic other)
        {
            _version = other._version;
            _name = other._name;
            _taskParameters = other._taskParameters;
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
    
        /// <summary>
        /// Name of the task logic
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("name")]
        [System.ComponentModel.DescriptionAttribute("Name of the task logic")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        /// <summary>
        /// Parameters of the task logic
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("taskParameters", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Parameters of the task logic")]
        public UclOpenHfVisualTaskParameters TaskParameters
        {
            get
            {
                return _taskParameters;
            }
            set
            {
                _taskParameters = value;
            }
        }
    
        public System.IObservable<UclOpenHfVisualTaskLogic> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenHfVisualTaskLogic(this)));
        }
    
        public System.IObservable<UclOpenHfVisualTaskLogic> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenHfVisualTaskLogic(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Version = " + _version + ", ");
            stringBuilder.Append("Name = " + _name + ", ");
            stringBuilder.Append("TaskParameters = " + _taskParameters);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UclOpenHfVisualTaskParameters
    {
    
        private double? _rngSeed;
    
        private System.Collections.Generic.List<string> _availableTextures;
    
        private string _interPresentationTexture;
    
        private double _presentationTime;
    
        private double _interPresentationTime;
    
        public UclOpenHfVisualTaskParameters()
        {
            _availableTextures = new System.Collections.Generic.List<string>();
        }
    
        protected UclOpenHfVisualTaskParameters(UclOpenHfVisualTaskParameters other)
        {
            _rngSeed = other._rngSeed;
            _availableTextures = other._availableTextures;
            _interPresentationTexture = other._interPresentationTexture;
            _presentationTime = other._presentationTime;
            _interPresentationTime = other._interPresentationTime;
        }
    
        /// <summary>
        /// Seed of the random number generator
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("rngSeed")]
        [System.ComponentModel.DescriptionAttribute("Seed of the random number generator")]
        public double? RngSeed
        {
            get
            {
                return _rngSeed;
            }
            set
            {
                _rngSeed = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("availableTextures", Required=Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.List<string> AvailableTextures
        {
            get
            {
                return _availableTextures;
            }
            set
            {
                _availableTextures = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("interPresentationTexture", Required=Newtonsoft.Json.Required.Always)]
        public string InterPresentationTexture
        {
            get
            {
                return _interPresentationTexture;
            }
            set
            {
                _interPresentationTexture = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("presentationTime", Required=Newtonsoft.Json.Required.Always)]
        public double PresentationTime
        {
            get
            {
                return _presentationTime;
            }
            set
            {
                _presentationTime = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("interPresentationTime", Required=Newtonsoft.Json.Required.Always)]
        public double InterPresentationTime
        {
            get
            {
                return _interPresentationTime;
            }
            set
            {
                _interPresentationTime = value;
            }
        }
    
        public System.IObservable<UclOpenHfVisualTaskParameters> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UclOpenHfVisualTaskParameters(this)));
        }
    
        public System.IObservable<UclOpenHfVisualTaskParameters> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UclOpenHfVisualTaskParameters(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("RngSeed = " + _rngSeed + ", ");
            stringBuilder.Append("AvailableTextures = " + _availableTextures + ", ");
            stringBuilder.Append("InterPresentationTexture = " + _interPresentationTexture + ", ");
            stringBuilder.Append("PresentationTime = " + _presentationTime + ", ");
            stringBuilder.Append("InterPresentationTime = " + _interPresentationTime);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Vector3
    {
    
        private double _x;
    
        private double _y;
    
        private double _z;
    
        public Vector3()
        {
        }
    
        protected Vector3(Vector3 other)
        {
            _x = other._x;
            _y = other._y;
            _z = other._z;
        }
    
        /// <summary>
        /// X coordinate of the point.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("x", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("X coordinate of the point.")]
        public double X
        {
            get
            {
                return _x;
            }
            set
            {
                _x = value;
            }
        }
    
        /// <summary>
        /// Y coordinate of the point.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("y", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Y coordinate of the point.")]
        public double Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }
    
        /// <summary>
        /// Z coordinate of the point.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("z", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Z coordinate of the point.")]
        public double Z
        {
            get
            {
                return _z;
            }
            set
            {
                _z = value;
            }
        }
    
        public System.IObservable<Vector3> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Vector3(this)));
        }
    
        public System.IObservable<Vector3> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Vector3(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("X = " + _x + ", ");
            stringBuilder.Append("Y = " + _y + ", ");
            stringBuilder.Append("Z = " + _z);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<DisplayCalibration> source)
        {
            return Process<DisplayCalibration>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayExtrinsics> source)
        {
            return Process<DisplayExtrinsics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DisplayIntrinsics> source)
        {
            return Process<DisplayIntrinsics>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Experiment> source)
        {
            return Process<Experiment>(source);
        }

        public System.IObservable<string> Process(System.IObservable<MatrixArduino> source)
        {
            return Process<MatrixArduino>(source);
        }

        public System.IObservable<string> Process(System.IObservable<MatrixArduinoData> source)
        {
            return Process<MatrixArduinoData>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Screen> source)
        {
            return Process<Screen>(source);
        }

        public System.IObservable<string> Process(System.IObservable<SpinnakerCamera> source)
        {
            return Process<SpinnakerCamera>(source);
        }

        public System.IObservable<string> Process(System.IObservable<SyncQuad> source)
        {
            return Process<SyncQuad>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenHfVisualRig> source)
        {
            return Process<UclOpenHfVisualRig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenHfVisualTaskLogic> source)
        {
            return Process<UclOpenHfVisualTaskLogic>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UclOpenHfVisualTaskParameters> source)
        {
            return Process<UclOpenHfVisualTaskParameters>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Vector3> source)
        {
            return Process<Vector3>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayCalibration>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayExtrinsics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DisplayIntrinsics>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Experiment>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<MatrixArduino>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<MatrixArduinoData>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Screen>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<SpinnakerCamera>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<SyncQuad>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenHfVisualRig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenHfVisualTaskLogic>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UclOpenHfVisualTaskParameters>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Vector3>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<DisplayCalibration>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }
}